name: SSH Test

on:
  workflow_dispatch:

jobs:
  ssh-test:
    runs-on: ubuntu-latest
    steps:
      - name: Decode SSH key
        run: |
          mkdir -p /root/.ssh
          ***REMOVED******REMOVED*** base64 -i ~/.ssh/aws_next_watch_may_7.pem | tr -d '\n' > encoded_key.txt
          ***REMOVED******REMOVED*** include in secrets
          echo "${{ secrets.KEY_BASE64 }}" | base64 -d > /root/.ssh/id_rsa
          chmod 600 /root/.ssh/id_rsa

      - name: Test SSH with appleboy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key_path: /root/.ssh/id_rsa
          script: |
            echo "✅ SSH via Appleboy works"
            hostname
