"""Command implementations for the CLI.

All commands are now auto-generated by the NextWatch CLI Framework:
- Health commands: Generated by create_health_commands()
- Cache commands: Imported from NextWatch Cache Library
- Version commands: Generated by create_version_command()
- Serve commands: Generated by create_serve_app()
- Config commands: Generated by create_config_command()

No custom command modules remain in this directory.
"""

# All commands are now generated by the CLI framework
# No custom command modules to import

__all__: list[str] = [
    # No custom commands - all generated by framework
]
