"""Avro schema definitions for Kafka events."""

from kafka.schemas.avro_schemas import (
    AVRO_SCHEMAS,
    CACHE_INVALIDATION_EVENT_SCHEMA,
    DLQ_EVENT_SCHEMA,
    ML_TRAINING_TRIGGER_EVENT_SCHEMA,
    MOVIE_CREATED_EVENT_SCHEMA,
    MOVIE_DELETED_EVENT_SCHEMA,
    MOVIE_RATED_EVENT_SCHEMA,
    MOVIE_UPDATED_EVENT_SCHEMA,
    MOVIE_VIEWED_EVENT_SCHEMA,
    RECOMMENDATION_REQUEST_EVENT_SCHEMA,
    SERVICE_HEALTH_EVENT_SCHEMA,
    USER_LOGIN_EVENT_SCHEMA,
    USER_LOGOUT_EVENT_SCHEMA,
    USER_REGISTERED_EVENT_SCHEMA,
    WATCHLIST_CHANGED_EVENT_SCHEMA,
)
from kafka.schemas.generator import generate_avro_schema_from_pydantic

__all__ = [
    "AVRO_SCHEMAS",
    "USER_REGISTERED_EVENT_SCHEMA",
    "USER_LOGIN_EVENT_SCHEMA",
    "USER_LOGOUT_EVENT_SCHEMA",
    "MOVIE_VIEWED_EVENT_SCHEMA",
    "MOVIE_RATED_EVENT_SCHEMA",
    "WATCHLIST_CHANGED_EVENT_SCHEMA",
    "MOVIE_CREATED_EVENT_SCHEMA",
    "MOVIE_UPDATED_EVENT_SCHEMA",
    "MOVIE_DELETED_EVENT_SCHEMA",
    "CACHE_INVALIDATION_EVENT_SCHEMA",
    "RECOMMENDATION_REQUEST_EVENT_SCHEMA",
    "ML_TRAINING_TRIGGER_EVENT_SCHEMA",
    "SERVICE_HEALTH_EVENT_SCHEMA",
    "DLQ_EVENT_SCHEMA",
    "generate_avro_schema_from_pydantic",
]
