{
 "title": "FastAPI Observability",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "service",
    "label": "Service",
    "query": {
     "query": "label_values(http_requests_total, service)"
    }
   },
   { "name": "log_keyword", "label": "Log Query" }
  ]
 },
 "panels": [
  {
   "title": "Total Requests",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_requests_total{service=~\"$service\"}[24h]))"
    }
   ]
  },
  {
   "title": "Requests Count",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (method, endpoint) (increase(http_requests_total{service=~\"$service\"}[24h]))",
     "legendFormat": "{{method}} {{endpoint}}"
    }
   ]
  },
  {
   "title": "Requests Average Duration",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (method, endpoint) (rate(http_request_duration_seconds_sum{service=~\"$service\"}[5m])) / sum by (method, endpoint) (rate(http_request_duration_seconds_count{service=~\"$service\"}[5m]))",
     "legendFormat": "{{method}} {{endpoint}}"
    }
   ]
  },
  {
   "title": "Total Exceptions",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_requests_total{service=~\"$service\", status_code=~\"5..\"}[24h]))"
    }
   ]
  },
  {
   "title": "Percent of 2xx Requests",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 4, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (endpoint) (rate(http_requests_total{service=~\"$service\", status_code=~\"2..\"}[5m])) / sum by (endpoint) (rate(http_requests_total{service=~\"$service\"}[5m]))",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "Percent of 5xx Requests",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (endpoint) (rate(http_requests_total{service=~\"$service\", status_code=~\"5..\"}[5m])) / sum by (endpoint) (rate(http_requests_total{service=~\"$service\"}[5m]))",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "PR 99 Requests Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le, endpoint) (rate(http_request_duration_seconds_bucket{service=~\"$service\"}[5m])))",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "Request In Process",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 13 },
   "targets": [
    {
     "expr": "sum by (service) (http_requests_in_progress{service=~\"$service\"})",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Request Per Sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (endpoint) (rate(http_requests_total{service=~\"$service\"}[1m]))",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "Log Type Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "sum by(level) (rate({environment=\"production\"} |= \"$log_keyword\" [1m]))",
     "legendFormat": "{{level}}"
    }
   ]
  },
  {
   "title": "Log of All FastAPI App",
   "type": "logs",
   "gridPos": { "h": 9, "w": 18, "x": 6, "y": 21 },
   "targets": [
    {
     "expr": "{environment=\"production\"} | line_format \"{{.service}}\\t{{.level}}\\t {{.msg}}\" |= \"$log_keyword\""
    }
   ]
  }
 ]
}