[mypy]
python_version = 3.9
warn_return_any = True
warn_unused_configs = True
disallow_untyped_defs = True
disallow_incomplete_defs = True
check_untyped_defs = True
disallow_untyped_decorators = True
no_implicit_optional = True
strict_optional = True
mypy_path = ./src
explicit_package_bases = True

***REMOVED*** Per-module options
[mypy.plugins.pydantic.*]
follow_imports = skip

[mypy.plugins.sqlmodel.*]
follow_imports = skip

***REMOVED*** Ignore certain modules that may not have stubs
[mypy.plugins.fastapi.*]
follow_imports = skip 