name: Build Application (Backend, Importer, Frontend)

on:
  workflow_dispatch:
    inputs:
      build_all:
        description: "Build all apps regardless of changes"
        required: false
        default: "false"
  push:
    paths:
      - "apps/backend-api/**"
      - "apps/data-importer/**"
      - "apps/web-nextjs/**"
  workflow_call:
    inputs:
      build_all:
        description: "Build all apps regardless of changes"
        required: false
        type: string
        default: "false"
    secrets:
      GH_PAT:
        required: true
    outputs:
      image_backend:
        description: "Backend API image"
        value: ${{ jobs.build_backend.outputs.image }}
      image_importer:
        description: "Data Importer image"
        value: ${{ jobs.build_importer.outputs.image }}
      image_frontend:
        description: "Frontend image"
        value: ${{ jobs.build_frontend.outputs.image }}

jobs:
  check_changes:
    runs-on: ubuntu-latest
    outputs:
      backend_changed: ${{ steps.filter.outputs.backend }}
      importer_changed: ${{ steps.filter.outputs.importer }}
      frontend_changed: ${{ steps.filter.outputs.frontend }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            backend:
              - 'apps/backend-api/**'
            importer:
              - 'apps/data-importer/**'
            frontend:
              - 'apps/web-nextjs/**'

  build_backend:
    needs: check_changes
    if: ${{ needs.check_changes.outputs.backend_changed == 'true' || github.event.inputs.build_all == 'true' }}
    uses: ./.github/workflows/build-app.yml
    with:
      app_name: backend-api
      dockerfile_path: ./apps/backend-api/Dockerfile
    secrets:
      GH_PAT: ${{ secrets.GH_PAT }}

  build_importer:
    needs: check_changes
    if: ${{ needs.check_changes.outputs.importer_changed == 'true' || github.event.inputs.build_all == 'true' }}
    uses: ./.github/workflows/build-app.yml
    with:
      app_name: data-importer
      dockerfile_path: ./apps/data-importer/Dockerfile
    secrets:
      GH_PAT: ${{ secrets.GH_PAT }}

  build_frontend:
    needs: check_changes
    if: ${{ needs.check_changes.outputs.frontend_changed == 'true' || github.event.inputs.build_all == 'true' }}
    uses: ./.github/workflows/build-app.yml
    with:
      app_name: frontend
      dockerfile_path: ./apps/web-nextjs/Dockerfile
      build_args: |
        NEXT_PUBLIC_API_URL=https://alexsandbox.me
    secrets:
      GH_PAT: ${{ secrets.GH_PAT }}
