name: Release

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      skip_registry: "false"
    secrets:
      GH_PAT: ${{ secrets.GH_PAT }}

  deploy:
    needs: build
    uses: ./.github/workflows/deploy.yml
    secrets:
      DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
      DEPLOY_HOST: ${{ secrets.DEPLOY_HOST }}
      DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
      GH_PAT: ${{ secrets.GH_PAT }}
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      JWT_JWK: ${{ secrets.JWT_JWK }}
      JWT_JWK_ROTATION_INTERVAL: ${{ secrets.JWT_JWK_ROTATION_INTERVAL }}
