name: SSH Test

on:
  workflow_dispatch:

jobs:
  ssh-test:
    runs-on: ubuntu-latest
    steps:
      - name: Restore SSH key from raw string
        run: |
          mkdir -p /root/.ssh
          echo "${{ secrets.KEY }}" | sed 's/\\n/\n/g' > /root/.ssh/id_rsa
          chmod 600 /root/.ssh/id_rsa

      - name: Test SSH with Appleboy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key_path: /root/.ssh/id_rsa
          script: |
            echo "✅ SSH via Appleboy works with normal key!"
            hostname
