name: SSH Test

on:
  workflow_dispatch:

jobs:
  ssh-test:
    runs-on: ubuntu-latest
    env:
      SSH_PATH: ${{ secrets.IS_ACT == 'true' && '/root/.ssh/id_rsa' || '/home/runner/.ssh/id_rsa' }}
      SSH_DIR: ${{ secrets.IS_ACT == 'true' && '/root/.ssh' || '/home/runner/.ssh' }}

    steps:
      - name: Restore SSH key from string
        run: |
          mkdir -p "$SSH_DIR"
          echo "${{ secrets.KEY }}" | sed 's/\\n/\n/g' > "$SSH_PATH"
          chmod 600 "$SSH_PATH"

      - name: Test SSH with Appleboy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key_path: ${{ env.SSH_PATH }}
          script: |
            echo "✅ SSH connection successful"
            hostname
